const {
  di: {
    dcmConfigModel: {
      nodeDataType: { BLOCK, TROUBLE, NONE },
    },
  },
} = require('../../../module');

/**
 * @type {mDeviceMap}
 */
const map = {
  drawInfo: {
    frame: {
      mapInfo: {
        width: 3000,
        height: 2000,
        backgroundInfo: {
          backgroundData: '',
          backgroundPosition: [160, 0],
        },
      },
      svgModelResourceList: [
        {
          id: 'solarEvaporationBlock',
          type: 'rect',
          elementDrawInfo: { width: 300, height: 230, color: '#abe3e1', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'normalEvaporationBlock_A',
          type: 'rect',
          elementDrawInfo: { width: 700, height: 130, color: '#bd8f3a', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'normalEvaporationBlock_B',
          type: 'rect',
          elementDrawInfo: { width: 700, height: 100, color: '#bd8f3a', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'normalEvaporationBlock_C',
          type: 'rect',
          elementDrawInfo: { width: 300, height: 230, color: '#bd8f3a', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'normalCrystalizingBlock',
          type: 'rect',
          elementDrawInfo: { width: 200, height: 160, color: '#988224', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'reservoir_A',
          type: 'rect',
          elementDrawInfo: { width: 770, height: 90, color: 'blue', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'reservoir_B',
          type: 'rect',
          elementDrawInfo: { width: 180, height: 90, color: 'blue', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'drainage',
          type: 'rect',
          elementDrawInfo: { width: 80, height: 90, color: 'skyblue', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'brineWarehouse_A',
          type: 'rect',
          elementDrawInfo: { width: 250, height: 80, color: '#90b4dd', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'brineWarehouse_B',
          type: 'rect',
          elementDrawInfo: { width: 200, height: 80, color: '#90b4dd', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'brineWarehouse_C',
          type: 'rect',
          elementDrawInfo: { width: 120, height: 80, color: '#90b4dd', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'brineWarehouse_D',
          type: 'rect',
          elementDrawInfo: { width: 110, height: 80, color: '#90b4dd', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'sea',
          type: 'rect',
          elementDrawInfo: { width: 770, height: 20, color: 'skyblue', opacity: 1 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'waterWay',
          type: 'line',
          elementDrawInfo: { width: 25, color: '#b2b2b2', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'waterWay_B',
          type: 'line',
          elementDrawInfo: { width: 25, color: '#4c7a89', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'peWaterWay',
          type: 'line',
          elementDrawInfo: { width: 25, color: '#108760', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'pipeLine_A',
          type: 'line',
          elementDrawInfo: { width: 10, color: '#ff9a00', opacity: 0 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'pipeLine_B',
          type: 'line',
          elementDrawInfo: { width: 10, color: '#7513a1', opacity: 1 },
          textStyleInfo: { color: '', fontSize: 10 },
        },
        {
          id: 'waterDoor',
          type: 'rect',
          elementDrawInfo: {
            width: 30,
            height: 30,
            color: ['#a3a3a3', '#b45b95', '#dc1d1f'],
            opacity: 1,
          },
          textStyleInfo: { color: '', fontSize: 5, leading: '1.8em' },
        },
        {
          id: 'gateValve',
          type: 'rect',
          elementDrawInfo: {
            width: 30,
            height: 30,
            color: ['#a3a3a3', 'yellow', '#dc1d1f'],
            opacity: 1,
          },
          textStyleInfo: { color: '', fontSize: 4, leading: '2.5em' },
        },
        {
          id: 'overPump',
          type: 'circle',
          elementDrawInfo: {
            width: 35,
            height: 35,
            radius: 35,
            color: ['#a3a3a3', '#22fb00', '#dc1d1f'],
            opacity: 1,
            leading: '10em',
          },
          textStyleInfo: { color: '', fontSize: 6 },
        },
        {
          id: 'underPump',
          type: 'circle',
          elementDrawInfo: {
            width: 27,
            height: 27,
            radius: 27,
            color: ['#a3a3a3', '#8b24b0', '#dc1d1f'],
            opacity: 1,
          },
          textStyleInfo: { color: '', fontSize: 6 },
        },
        {
          id: 'outlet',
          type: 'circle',
          elementDrawInfo: { width: 10, height: 10, radius: 10, color: 'black', opacity: 1 },
          textStyleInfo: { color: '', fontSize: 8 },
        },
        {
          id: 'salinity',
          type: 'rect',
          elementDrawInfo: { width: 45, height: 25, color: '#f0f0f0', opacity: 1 },
          textStyleInfo: { color: '', fontSize: 8 },
        },
        {
          id: 'moduleRearTemperature',
          type: 'rect',
          elementDrawInfo: { width: 45, height: 25, color: '#f0f0f0', opacity: 1 },
          textStyleInfo: { color: '', fontSize: 5 },
        },
        {
          id: 'waterLevel',
          type: 'rect',
          elementDrawInfo: { width: 45, height: 25, color: '#f0f0f0', opacity: 1 },
          textStyleInfo: { color: '', fontSize: 8 },
        },
        {
          id: 'brineTemperature',
          type: 'rect',
          elementDrawInfo: { width: 45, height: 25, color: '#f0f0f0', opacity: 1 },
          textStyleInfo: { color: '', fontSize: 8 },
        },
      ],
    },
    positionInfo: {
      svgPlaceList: [
        {
          placeId: 'salternBlock',
          svgPositonList: [
            {
              id: 'SEB_1',
              name: '증발지_1',
              resourceId: 'solarEvaporationBlock',
              point: [200, 640],
            },
            {
              id: 'NEB_1',
              name: '일반 증발지_1',
              resourceId: 'normalEvaporationBlock_A',
              point: [200, 170],
            },
            {
              id: 'NEB_2',
              name: '일반 증발지_2',
              resourceId: 'normalEvaporationBlock_B',
              point: [200, 310],
            },
            {
              id: 'NEB_3',
              name: '일반 증발지_3',
              resourceId: 'normalEvaporationBlock_C',
              point: [600, 640],
            },
            {
              id: 'NCB',
              name: '결정지',
              resourceId: 'normalCrystalizingBlock',
              point: [200, 920],
            },
          ],
        },
        {
          placeId: 'brineWarehouse',
          svgPositonList: [
            { id: 'BW_1', name: '해주_1', resourceId: 'brineWarehouse_A', point: [200, 450] },
            { id: 'BW_2', name: '해주_2', resourceId: 'brineWarehouse_B', point: [460, 450] },
            { id: 'BW_5', name: '해주_5', resourceId: 'brineWarehouse_D', point: [445, 930] },
          ],
        },
        {
          placeId: 'reservoir',
          svgPositonList: [
            { id: 'RV_1', name: '저수지_1', resourceId: 'reservoir_A', point: [170, 40] },
          ],
        },
        {
          placeId: 'sea',
          svgPositonList: [{ id: 'SEA', name: '바다', resourceId: 'sea', point: [170, 10] }],
        },
        {
          placeId: 'waterWay',
          svgPositonList: [
            {
              id: 'WW_001',
              name: '수로_001',
              resourceId: 'waterWay',
              point: [170, 155, 930, 155],
            },
            {
              id: 'WW_002',
              name: '수로_002',
              resourceId: 'waterWay',
              point: [182, 160, 182, 1113],
            },
            {
              id: 'WW_003',
              name: '수로_003',
              resourceId: 'waterWay',
              point: [930, 142, 930, 1113],
            },
            {
              id: 'WW_004',
              name: '수로_004',
              resourceId: 'waterWay',
              point: [170, 610, 930, 610],
            },
            {
              id: 'WW_006',
              name: '수로_006',
              resourceId: 'waterWay',
              point: [170, 900, 930, 900],
            },
            {
              id: 'WW_007',
              name: '수로_007',
              resourceId: 'waterWay',
              point: [170, 1100, 930, 1100],
            },
            {
              id: 'WW_009',
              name: '수로_009',
              resourceId: 'peWaterWay',
              point: [435, 410, 435, 432],
            },
            {
              id: 'WW_010',
              name: '수로_010',
              resourceId: 'peWaterWay',
              point: [435, 432, 435, 450],
            },
            {
              id: 'WW_011',
              name: '수로_011',
              resourceId: 'peWaterWay',
              point: [435, 432, 475, 432],
            },
            {
              id: 'WW_012',
              name: '수로_012',
              resourceId: 'peWaterWay',
              point: [475, 410, 475, 432],
            },
            {
              id: 'WW_013',
              name: '수로_013',
              resourceId: 'peWaterWay',
              point: [475, 432, 475, 450],
            },
            {
              id: 'WW_014',
              name: '수로_014',
              resourceId: 'peWaterWay',
              point: [400, 950, 425, 950],
            },
            {
              id: 'WW_015',
              name: '수로_015',
              resourceId: 'peWaterWay',
              point: [425, 950, 450, 950],
            },
            {
              id: 'WW_016',
              name: '수로_016',
              resourceId: 'peWaterWay',
              point: [425, 950, 425, 910],
            },
            {
              id: 'WW_017',
              name: '수로_017',
              resourceId: 'waterWay_B',
              point: [475, 530, 475, 570],
            },
            {
              id: 'WW_020',
              name: '수로_020',
              resourceId: 'waterWay_B',
              point: [230, 570, 488, 570],
            },
            {
              id: 'WW_021',
              name: '수로_021',
              resourceId: 'waterWay_B',
              point: [242, 565, 242, 640],
            },
            {
              id: 'WW_022',
              name: '수로_022',
              resourceId: 'waterWay_B',
              point: [250, 610, 300, 610],
            },
          ],
        },
        {
          placeId: 'pipeLine',
          svgPositonList: [],
        },
      ],
      svgNodeList: [],
    },
  },
  setInfo: {
    mainInfo: { main_seq: 2, uuid: 'bbbbb' },
    dccConstructorList: [
      {
        dccId: 'DCC_TEST_001',
        dccName: '테스트 용',
        connect_info: { type: 'socket', subType: '', host: 'localhost', port: 9000 },
      },
      {
        dccId: 'DCC_SSCS_001',
        dccName: '수중 태양광 장치 로거',
        connect_info: {
          type: 'zigbee',
          subType: 'xbee',
          baudRate: 9600,
          port: 'COM6',
          // retryChance: 5,
        },
      },
      {
        dccId: 'DCC_CNT_001',
        dccName: '접속반 로거 A',
        connect_info: { type: 'modbus', subType: 'rtu', baudRate: 9600, port: 'COM4' },
      },
      {
        dccId: 'DCC_CNT_002',
        dccName: '접속반 로거 B',
        connect_info: { type: 'modbus', subType: 'rtu', baudRate: 9600, port: 'COM4' },
      },
      {
        dccId: 'DCC_CNT_003',
        dccName: '접속반 로거 C',
        connect_info: { type: 'modbus', subType: 'rtu', baudRate: 9600, port: 'COM4' },
      },
      {
        dccId: 'DCC_CNT_004',
        dccName: '접속반 로거 D',
        connect_info: { type: 'modbus', subType: 'rtu', baudRate: 9600, port: 'COM4' },
      },
      {
        dccId: 'DCC_IVT_001',
        dccName: '인버터 로거 A',
        connect_info: {
          type: 'serial',
          subType: 'parser',
          baudRate: 9600,
          port: 'COM3',
          addConfigInfo: {
            parser: 'delimiterParser',
            option: Buffer.from([0x04]),
          },
        },
      },
      {
        dccId: 'DCC_IVT_002',
        dccName: '인버터 로거 B',
        connect_info: {
          type: 'serial',
          subType: 'parser',
          baudRate: 9600,
          port: 'COM3',
          addConfigInfo: {
            parser: 'delimiterParser',
            option: Buffer.from([0x04]),
          },
        },
      },
      {
        dccId: 'DCC_IVT_003',
        dccName: '인버터 로거 C',
        connect_info: {
          type: 'serial',
          subType: 'parser',
          baudRate: 9600,
          port: 'COM3',
          addConfigInfo: {
            parser: 'delimiterParser',
            option: Buffer.from([0x04]),
          },
        },
      },
      {
        dccId: 'DCC_IVT_004',
        dccName: '인버터 로거 D',
        connect_info: {
          type: 'serial',
          subType: 'parser',
          baudRate: 9600,
          port: 'COM3',
          addConfigInfo: {
            parser: 'delimiterParser',
            option: Buffer.from([0x04]),
          },
        },
      },
    ],
    dpcConstructorList: [
      { dpcId: 'DPC_001', protocol_info: { mainCategory: 'UPSAS', subCategory: 'xbee' } },
      { dpcId: 'DPC_002', protocol_info: { mainCategory: 'UPSAS', subCategory: 'muan100kW' } },
      {
        dpcId: 'DPC_IVT_001',
        protocol_info: { mainCategory: 'Inverter', subCategory: 'hexPowerTriple' },
      },
      { dpcId: 'DPC_CNT_001', protocol_info: { mainCategory: 'Sensor', subCategory: 'CNT_dm_v1' } },
      {
        dpcId: 'DPC_CNT_002',
        protocol_info: { mainCategory: 'Sensor', subCategory: 'CNT_DK_v2.2' },
      },
    ],
    repeatNodeList: [
      {
        repeatId: 'RE_NODE_IVT',
        repeatCategory: 'node',
        nodeList: [],
      },
      {
        repeatId: 'RE_PREFIX_IVT',
        repeatCategory: 'prefix',
        nodeList: [
          'IVT_PV_V',
          'IVT_PV_A',
          'IVT_PV_KW',
          'IVT_G_RS_V',
          'IVT_G_ST_V',
          'IVT_G_TR_V',
          'IVT_G_R_A',
          'IVT_G_S_A',
          'IVT_G_T_A',
          'IVT_G_L_F',
          'IVT_PW_PV_KW',
          'IVT_PW_G_KW',
          'IVT_PW_C_KWH',
          'IVT_TRB',
        ],
      },
      {
        repeatId: 'RE_NODE_CNT',
        repeatCategory: 'node',
        nodeList: [],
      },
      {
        repeatId: 'RE_PREFIX_CNT',
        repeatCategory: 'prefix',
        nodeList: [
          'CNT_A_1CH',
          'CNT_V_1CH',
          'CNT_A_2CH',
          'CNT_V_2CH',
          'CNT_A_3CH',
          'CNT_V_3CH',
          'CNT_A_4CH',
          'CNT_V_4CH',
          'CNT_A_5CH',
          'CNT_V_5CH',
          'CNT_A_6CH',
          'CNT_V_6CH',
        ],
      },
    ],
    dataLoggerStructureList: [
      {
        target_prefix: 'D_G',
        target_name: '수문 DL',
        dataLoggerDeviceList: [
          {
            serial_number: '0013A20040F70001',
            target_code: '001',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70002',
            target_code: '002',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['WD_002'],
          },
          {
            serial_number: '0013A20040F70003',
            target_code: '003',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70004',
            target_code: '004',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['WD_004'],
          },
          {
            serial_number: '0013A20040F70005',
            target_code: '005',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['WD_005'],
          },
          {
            serial_number: '0013A20040F70006',
            target_code: '006',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['WD_006'],
          },
          {
            serial_number: '0013A20040F70007',
            target_code: '007',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['WD_007'],
          },
          {
            serial_number: '0013A20040F70008',
            target_code: '008',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['WD_008'],
          },
        ],
      },
      {
        target_prefix: 'D_GV',
        target_name: '게이트형 밸브',
        dataLoggerDeviceList: [
          {
            serial_number: '0013A20040F70101',
            target_code: '101',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70102',
            target_code: '102',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70103',
            target_code: '103',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70104',
            target_code: '104',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70105',
            target_code: '105',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['GV_105'],
          },
          {
            serial_number: '0013A20040F70106',
            target_code: '106',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['GV_106', 'S_002', 'WL_009', 'MRT_001', 'BT_001'],
          },
          {
            serial_number: '0013A20040F70107',
            target_code: '107',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['GV_107'],
          },
          {
            serial_number: '0013A20040F70108',
            target_code: '108',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70109',
            target_code: '109',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70110',
            target_code: '110',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70111',
            target_code: '111',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70112',
            target_code: '112',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70113',
            target_code: '113',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70114',
            target_code: '114',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70115',
            target_code: '115',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70116',
            target_code: '116',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70117',
            target_code: '117',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70118',
            target_code: '118',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70119',
            target_code: '119',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F70120',
            target_code: '120',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
        ],
      },
      {
        target_prefix: 'D_P',
        target_name: '펌프 DL',
        dataLoggerDeviceList: [
          {
            serial_number: '0013A20040F72001',
            target_code: '001',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['P_001'],
          },
          {
            serial_number: '0013A20040F72002',
            target_code: '002',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F72003',
            target_code: '003',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F72004',
            target_code: '004',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['P_004'],
          },
          {
            serial_number: '0013A20040F72005',
            target_code: '005',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F72006',
            target_code: '006',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F72007',
            target_code: '007',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F72008',
            target_code: '008',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F72009',
            target_code: '009',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F72010',
            target_code: '010',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F72011',
            target_code: '011',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F72012',
            target_code: '012',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F72013',
            target_code: '013',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: ['P_013'],
          },
        ],
      },
      {
        target_prefix: 'D_S',
        target_name: '센서 ',
        dataLoggerDeviceList: [
          {
            serial_number: '0013A20040F71001',
            target_code: '001',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F71002',
            target_code: '002',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F71003',
            target_code: '003',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F71004',
            target_code: '004',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F71005',
            target_code: '005',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F71006',
            target_code: '006',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F71007',
            target_code: '007',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F71008',
            target_code: '008',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F71009',
            target_code: '009',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
          {
            serial_number: '0013A20040F71010',
            target_code: '010',
            isAddSerialNumberToDCC: false,
            dccId: 'DCC_SSCS_001',
            dpcId: 'DPC_002',
            nodeList: [],
          },
        ],
      },
      {
        target_prefix: 'D_IVT',
        target_name: '인버터 DL',
        dataLoggerDeviceList: [
          {
            target_name: 'A (25kW 급)',
            serial_number: '01',
            target_code: '001',
            dccId: 'DCC_IVT_001',
            dpcId: 'DPC_IVT_001',
            repeatId: 'RE_PREFIX_IVT',
          },
          {
            target_name: 'B (25kW 급)',
            serial_number: '02',
            target_code: '002',
            dccId: 'DCC_IVT_002',
            dpcId: 'DPC_IVT_001',
            repeatId: 'RE_PREFIX_IVT',
          },
          {
            target_name: 'C (25kW 급)',
            serial_number: '03',
            target_code: '003',
            dccId: 'DCC_IVT_003',
            dpcId: 'DPC_IVT_001',
            repeatId: 'RE_PREFIX_IVT',
          },
          {
            target_name: 'D (25kW 급)',
            serial_number: '04',
            target_code: '004',
            dccId: 'DCC_IVT_004',
            dpcId: 'DPC_IVT_001',
            repeatId: 'RE_PREFIX_IVT',
          },
        ],
      },
      {
        target_prefix: 'D_CNT',
        target_name: '접속반',
        dataLoggerDeviceList: [
          {
            serial_number: 1,
            target_code: '001',
            dccId: 'DCC_CNT_001',
            dpcId: 'DPC_CNT_002',
            repeatId: 'RE_PREFIX_CNT',
          },
          {
            serial_number: 2,
            target_code: '002',
            dccId: 'DCC_CNT_002',
            dpcId: 'DPC_CNT_002',
            repeatId: 'RE_PREFIX_CNT',
          },
          {
            serial_number: 3,
            target_code: '003',
            dccId: 'DCC_CNT_003',
            dpcId: 'DPC_CNT_002',
            repeatId: 'RE_PREFIX_CNT',
          },
          {
            serial_number: 4,
            target_code: '004',
            dccId: 'DCC_CNT_004',
            dpcId: 'DPC_CNT_002',
            repeatId: 'RE_PREFIX_CNT',
          },
        ],
      },
    ],
    nodeStructureList: [
      // 수중 태양광 데이터
      {
        target_id: 'temp',
        target_name: '온도',
        is_sensor: 1,
        data_unit: '℃',
        description: '섭씨',
        defList: [
          {
            target_id: 'brineTemperature',
            target_prefix: 'BT',
            target_name: '염수 온도',
            nodeList: [{ target_code: '001', axisScale: [0, 0], moveScale: [-1, 0] }],
          },
          {
            target_id: 'moduleRearTemperature',
            target_prefix: 'MRT',
            target_name: '모듈 뒷면 온도',
            description: null,
            nodeList: [{ target_code: '001', axisScale: [0, 0], moveScale: [1, 1.5] }],
          },
        ],
      },
      {
        target_id: 'salinity',
        target_name: '염도',
        is_sensor: 1,
        data_unit: '%',
        defList: [
          {
            target_id: 'salinity',
            target_prefix: 'S',
            target_name: '염도',
            description: null,
            nodeList: [{ target_code: '002', axisScale: [0, 0], moveScale: [1, -1.5] }],
          },
        ],
      },
      {
        target_id: 'waterLevel',
        target_name: '수위',
        is_sensor: 1,
        data_unit: 'cm',
        defList: [
          {
            target_id: 'waterLevel',
            target_prefix: 'WL',
            target_name: '수위',
            nodeList: [{ target_code: '009', axisScale: [0, 0], moveScale: [-1, 0] }],
          },
        ],
      },
      {
        target_id: 'waterDoor',
        target_name: '수문',
        is_sensor: 0,
        defList: [
          {
            target_id: 'waterDoor',
            target_prefix: 'WD',
            target_name: '수문',
            nodeList: [
              { target_code: '002', axisScale: [0, 1], moveScale: [6.4, 0.7] },
              { target_code: '004', axisScale: [0, 1], moveScale: [-0.5, 0] },
              { target_code: '005', axisScale: [1, 0], moveScale: [0, 0] },
              { target_code: '006', axisScale: [0, 0], moveScale: [0, 0] },
              { target_code: '007', axisScale: [1, 0], moveScale: [0.25, -0.1] },
              { target_code: '008', axisScale: [0, 0], moveScale: [-0.1, -0.8] },
            ],
          },
        ],
      },
      {
        target_id: 'valve',
        target_name: '밸브',
        is_sensor: 0,
        defList: [
          {
            target_id: 'gateValve',
            target_prefix: 'GV',
            target_name: '수문 용 밸브',
            description: '파이프 관에 연결된 밸브, 직경 100A PVC 용 밸브',
            nodeList: [
              { target_code: '105', axisScale: [0, 0], moveScale: [-0.1, 0.5] },
              { target_code: '106', axisScale: [1, 0], moveScale: [0, 0] },
            ],
          },
        ],
      },
      {
        target_id: 'pump',
        target_name: '펌프',
        is_sensor: 0,
        defList: [
          {
            target_id: 'pump',
            target_prefix: 'P',
            target_name: '펌프',
            nodeList: [
              { target_code: '001', axisScale: [1, 1], moveScale: [-2.3, 0] },
              { target_code: '004', axisScale: [0, 1], moveScale: [1.7, 0] },
              { target_code: '013', axisScale: [0, 1], moveScale: [0, 0] },
            ],
          },
        ],
      },
      {
        target_id: 'outlet',
        target_name: '배출구',
        is_sensor: -1,
        is_submit_api: 0,
        save_db_type: 'none',
        description: '펌프의 배수구를 표현하기 위한 SVG 용 Element',
        defList: [
          {
            target_id: 'outlet',
            target_prefix: 'O',
            target_name: '배출구',
            nodeList: [
              { target_code: '002', axisScale: [1, 0], moveScale: [-5.2, 0] },
              { target_code: '004', axisScale: [1, 0], moveScale: [6, 0] },
              { target_code: '012', axisScale: [1, 0.5], moveScale: [0, 0] },
            ],
          },
        ],
      },
      {
        target_id: 'groundRelay',
        target_name: '지락 계전기',
        is_sensor: 1,
        defList: [
          {
            target_id: 'isConnectorGroundRelay',
            target_prefix: 'CGR',
            target_name: '접속반 지락 계전기',
            nodeList: [],
          },
        ],
      },
      // FIXME: 전류, 전압
      {
        target_id: 'vol',
        target_name: '전압',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: BLOCK,
        data_unit: 'V',
        description: null,
        defList: [
          {
            target_id: 'volCh1',
            target_name: '접속반 1 CH 전압',
            target_prefix: 'CNT_V_1CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'volCh2',
            target_name: '접속반 2 CH 전압',
            target_prefix: 'CNT_V_2CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'volCh3',
            target_name: '접속반 3 CH 전압',
            target_prefix: 'CNT_V_3CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'volCh4',
            target_name: '접속반 4 CH 전압',
            target_prefix: 'CNT_V_4CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'volCh5',
            target_name: '접속반 5 CH 전압',
            target_prefix: 'CNT_V_5CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'volCh6',
            target_name: '접속반 6 CH 전압',
            target_prefix: 'CNT_V_6CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'pvVol',
            target_name: '인버터 PV 전압',
            target_prefix: 'IVT_PV_V',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridRsVol',
            target_name: 'RS 선간 전압',
            target_prefix: 'IVT_G_RS_V',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridStVol',
            target_name: 'ST 선간 전압',
            target_prefix: 'IVT_G_ST_V',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridTrVol',
            target_name: 'TR 선간 전압',
            target_prefix: 'IVT_G_TR_V',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
      {
        target_id: 'amp',
        target_name: '전류',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: BLOCK,
        data_unit: 'A',
        description: null,
        defList: [
          {
            target_id: 'ampCh1',
            target_name: '접속반 1 CH 전류',
            target_prefix: 'CNT_A_1CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'ampCh2',
            target_name: '접속반 2 CH 전류',
            target_prefix: 'CNT_A_2CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'ampCh3',
            target_name: '접속반 3 CH 전류',
            target_prefix: 'CNT_A_3CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'ampCh4',
            target_name: '접속반 4 CH 전류',
            target_prefix: 'CNT_A_4CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'ampCh5',
            target_name: '접속반 5 CH 전류',
            target_prefix: 'CNT_A_5CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'ampCh6',
            target_name: '접속반 6 CH 전류',
            target_prefix: 'CNT_A_6CH',
            repeatId: 'RE_NODE_CNT',
          },
          {
            target_id: 'pvAmp',
            target_name: '인버터 PV 전류',
            target_prefix: 'IVT_PV_A',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridRAmp',
            target_name: '인버터 R상 전류',
            target_prefix: 'IVT_G_R_A',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridSAmp',
            target_name: '인버터 S상 전류',
            target_prefix: 'IVT_G_S_A',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'gridTAmp',
            target_name: '인버터 T상 전류',
            target_prefix: 'IVT_G_T_A',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
      {
        target_id: 'kW',
        target_name: '전력량',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: BLOCK,
        data_unit: 'kW',
        description: '1 킬로와트(기호 kW)는 1 초 동안의 1,000 줄(N·m)에 해당하는 일률의 SI 단위',
        defList: [
          {
            target_id: 'pvKw',
            target_name: '인버터 PV 출력',
            target_prefix: 'IVT_PV_KW',
            description: 'PV',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'powerGridKw',
            target_name: '인버터 현재 전력',
            target_prefix: 'IVT_PW_G_KW',
            description: 'Power',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
      {
        target_id: 'kWh',
        target_name: '전력량',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: BLOCK,
        data_unit: 'kWh',
        description: '시간당 에너지 단위, 1 kW의 일률로 1 시간 동안 하는 일의 양',
        defList: [
          {
            target_id: 'powerDailyKwh',
            target_name: '인버터 하루 발전량',
            target_prefix: 'IVT_PW_D_KWH',
            repeatId: 'RE_NODE_IVT',
          },
          {
            target_id: 'powerCpKwh',
            target_name: '인버터 누적 발전량',
            target_prefix: 'IVT_PW_C_KWH',
            description: 'Cumulative Power Generation',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
      {
        target_id: 'frequency',
        target_name: '주파수',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: BLOCK,
        data_unit: 'Hz',
        defList: [
          {
            target_id: 'gridLf',
            target_name: '계통 주파수',
            target_prefix: 'IVT_G_L_F',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
      {
        target_id: 'trouble',
        target_name: '오류 목록',
        is_sensor: 2,
        is_submit_api: 0,
        save_db_type: TROUBLE,
        description: '장치에서 보내오는 이상 데이터',
        defList: [
          {
            target_id: 'operTroubleList',
            target_name: '인버터 에러',
            target_prefix: 'IVT_TRB',
            repeatId: 'RE_NODE_IVT',
          },
        ],
      },
    ],
  },
  relationInfo: {
    placeRelationList: [
      {
        target_id: 'inverter',
        target_name: '인버터',
        description: '인버터를 설치한 공간',
        defList: [
          {
            target_id: 'inverter',
            target_prefix: 'P_IVT',
            placeList: [
              {
                target_code: '001',
                target_name: 'SK 쏠라 (25kW 급)',
                chart_color: '#212529',
                chart_sort_rank: 1,
                repeatId: 'RE_PREFIX_IVT',
              },
              {
                target_code: '002',
                target_name: '쏠라 테크 A (25kW 급)',
                chart_color: '#fcc2d7',
                chart_sort_rank: 2,
                repeatId: 'RE_PREFIX_IVT',
              },
              {
                target_code: '003',
                target_name: '쏠라 테크 B (25kW 급)',
                chart_color: '#d0bfff',
                chart_sort_rank: 3,
                repeatId: 'RE_PREFIX_IVT',
              },
              {
                target_code: '004',
                target_name: '쏠라 테크 C (25kW 급)',
                chart_color: '#99e9f2',
                chart_sort_rank: 4,
                repeatId: 'RE_PREFIX_IVT',
              },
            ],
          },
        ],
      },
      {
        target_id: 'connector',
        target_name: '접속반',
        defList: [
          {
            target_id: 'connector',
            target_prefix: 'P_CNT',
            placeList: [
              {
                target_code: '001',
                target_name: 'SK 쏠라 (25kW 급)',
                chart_sort_rank: 1,
                chart_color: '#212529',
                repeatId: 'RE_PREFIX_CNT',
              },
              {
                target_code: '002',
                target_name: '쏠라테크 A (25kW 급)',
                chart_color: '#fcc2d7',
                chart_sort_rank: 2,
                repeatId: 'RE_PREFIX_CNT',
              },
              {
                target_code: '003',
                target_name: '쏠라테크 B (25kW 급)',
                chart_color: '#d0bfff',
                chart_sort_rank: 3,
                repeatId: 'RE_PREFIX_CNT',
              },
              {
                target_code: '004',
                target_name: '쏠라테크 C (25kW 급)',
                chart_color: '#99e9f2',
                chart_sort_rank: 4,
                repeatId: 'RE_PREFIX_CNT',
              },
            ],
          },
        ],
      },
      {
        target_id: 'salternBlock',
        target_name: '염판',
        description: null,
        defList: [
          {
            target_id: 'solarEvaporationBlock',
            target_prefix: 'SEB',
            target_name: '수중 태양광 발전 증발지',
            placeList: [
              {
                target_code: '1',
                nodeList: ['S_002', 'WL_009', 'MRT_001', 'BT_001', 'O_004'],
                depth: 5,
                place_info: {
                  thresholdConfigList: [
                    {
                      ndId: 'waterLevel',
                      maxValue: { value: 10, isCall: false },
                      upperLimitValue: { value: 7, isCall: false },
                      setValue: { value: 5 },
                      lowerLimitValue: { value: 2.9, isCall: true },
                      minValue: { value: 1, isCall: true },
                      callPlaceRankList: ['BW_2'],
                      putPlaceRankList: ['BW_2', 'SEA'],
                    },
                    {
                      ndId: 'salinity',
                      upperLimitValue: { value: 10.5, isCall: false, isGroup: true },
                      putPlaceRankList: ['BW_2'],
                      groupPlaceList: ['SEB_1'],
                    },
                    {
                      ndId: 'moduleRearTemperature',
                      upperLimitValue: { value: 40, isCall: true },
                      callPlaceRankList: ['BW_2'],
                      putPlaceRankList: ['BW_2'],
                    },
                  ],
                  placeSize: { width: 356, height: 2800, depth: 15 },
                },
              },
            ],
          },
          {
            target_id: 'normalEvaporationBlock',
            target_prefix: 'NEB',
            target_name: '일반 증발지',
            placeList: [
              {
                target_code: '1',
                nodeList: ['WD_002', 'O_002'],
                depth: 5,
                place_info: {
                  thresholdConfigList: [
                    {
                      ndId: 'waterLevel',
                      maxValue: { value: 20 },
                      setValue: { value: 10 },
                      lowerLimitValue: { value: 3, isCall: true },
                      minValue: { value: 2, isCall: true },
                      callPlaceRankList: ['RV_1'],
                      putPlaceRankList: ['NEB_2'],
                    },
                  ],
                  placeSize: { width: 2500, height: 2000, depth: 20 },
                },
              },
              {
                target_code: '2',
                nodeList: ['WD_004'],
                depth: 4,
                place_info: {
                  thresholdConfigList: [
                    {
                      ndId: 'waterLevel',
                      maxValue: { value: 20 },
                      setValue: { value: 12 },
                      lowerLimitValue: { value: 3, isCall: true },
                      minValue: { value: 2, isCall: true },
                      callPlaceRankList: ['BW_1', 'NEB_1'],
                      putPlaceRankList: ['BW_1', 'SEA'],
                    },
                    {
                      ndId: 'salinity',
                      upperLimitValue: { value: 6, isCall: false },
                      putPlaceRankList: ['BW_2', 'BW_1'],
                    },
                  ],
                  placeSize: { width: 2500, height: 1000, depth: 20 },
                },
              },
            ],
          },
          {
            target_id: 'normalCrystalizingBlock',
            target_prefix: 'NCB',
            target_name: '일반 결정지',
            placeList: [
              {
                target_code: '',
                nodeList: ['O_012'],
                depth: 0,
                place_info: {
                  thresholdConfigList: [
                    {
                      ndId: 'waterLevel',
                      maxValue: { value: 10 },
                      setValue: { value: 5 },
                      minValue: { value: 1 },
                      callPlaceRankList: ['BW_5'],
                      putPlaceRankList: ['BW_5', 'SEA'],
                    },
                  ],
                  placeSize: { width: 800, height: 1000, depth: 20 },
                },
              },
            ],
          },
        ],
      },
      {
        target_id: 'brineWarehouse',
        target_name: '해주',
        description: null,
        defList: [
          {
            target_id: 'brineWarehouse',
            target_prefix: 'BW',
            target_name: '해주',
            placeList: [
              {
                target_code: '1',
                nodeList: ['WD_005'],
                depth: -1,
                place_info: {
                  thresholdConfigList: [
                    {
                      ndId: 'waterLevel',
                      maxValue: { value: 150 },
                      minValue: { value: 10 },
                      callPlaceRankList: ['NEB_2'],
                      putPlaceRankList: ['NEB_2'],
                    },
                  ],
                  placeSize: { width: 1200, height: 300, depth: 150 },
                },
              },
              {
                target_code: '2',
                nodeList: ['WD_006', 'P_004'],
                depth: -1,
                place_info: {
                  thresholdConfigList: [
                    {
                      ndId: 'waterLevel',
                      maxValue: { value: 150 },
                      minValue: { value: 10 },
                      callPlaceRankList: ['NEB_2'],
                      putPlaceRankList: ['SEB_1'],
                    },
                  ],
                  placeSize: { width: 900, height: 300, depth: 150 },
                },
              },
              {
                target_code: '5',
                nodeList: ['P_013'],
                depth: -1,
                place_info: {
                  thresholdConfigList: [
                    {
                      ndId: 'waterLevel',
                      maxValue: { value: 150 },
                      minValue: { value: 10 },
                      callPlaceRankList: ['BW_5'],
                      putPlaceRankList: ['NCB_1'],
                    },
                  ],
                  placeSize: { width: 500, height: 300, depth: 150 },
                },
              },
            ],
          },
        ],
      },
      {
        target_id: 'reservoir',
        target_name: '저수지',
        description: null,
        defList: [
          {
            target_id: 'reservoir',
            target_prefix: 'RV',
            target_name: '저수지',
            placeList: [
              {
                target_code: '1',
                nodeList: ['P_001'],
                depth: -1,
                place_info: {
                  thresholdConfigList: [
                    {
                      ndId: 'waterLevel',
                      maxValue: { value: 200 },
                      minValue: { value: 10 },
                      callPlaceRankList: [],
                      putPlaceRankList: ['NEB_1'],
                    },
                  ],
                  placeSize: { width: 4800, height: 570, depth: 200 },
                },
              },
            ],
          },
        ],
      },
      {
        target_id: 'sea',
        target_name: '바다',
        description: null,
        defList: [
          {
            target_id: 'sea',
            target_prefix: 'SEA',
            target_name: '바다',
            placeList: [{ target_code: '', depth: -1, nodeList: [], place_info: {} }],
          },
        ],
      },
      {
        target_id: 'waterWay',
        target_name: '수로',
        description: null,
        defList: [
          {
            target_id: 'waterWay',
            target_prefix: 'WW',
            target_name: '수로',
            placeList: [
              { target_code: '001', nodeList: [], depth: 0.2 },
              { target_code: '002', nodeList: [], depth: 0.3 },
              { target_code: '003', nodeList: [], depth: 0.3 },
              { target_code: '004', nodeList: [], depth: 0.6 },
              { target_code: '005', nodeList: [], depth: 0.5 },
              { target_code: '006', nodeList: [], depth: 0.4 },
              { target_code: '007', nodeList: [], depth: 0.5 },
              { target_code: '009', nodeList: [], depth: 0.5 },
              { target_code: '010', nodeList: ['WD_005'], depth: 0.3 },
              { target_code: '011', nodeList: ['WD_005'], depth: 0.4 },
              { target_code: '012', nodeList: [], depth: 0.5 },
              { target_code: '013', nodeList: ['WD_006'], depth: 0.3 },
              { target_code: '014', nodeList: [], depth: 0.8 },
              { target_code: '015', nodeList: ['WD_007'], depth: 0.8 },
              { target_code: '016', nodeList: ['WD_008'], depth: 0.7 },
              { target_code: '021', nodeList: ['GV_105'], depth: 0.8 },
              { target_code: '022', nodeList: ['GV_106'], depth: 0.7 },
            ],
          },
        ],
      },
      {
        target_id: 'pipeLine',
        target_name: '파이프',
        description: null,
        defList: [
          {
            target_id: 'pipeLine',
            target_prefix: 'PL',
            target_name: '파이프',
            placeList: [],
          },
        ],
      },
    ],
    smartSalternInfo: {
      pipeConnectionRelationList: [
        { currNode: 'P_001', parentNodes: [], childNodes: ['O_002'] },
        { currNode: 'P_004', parentNodes: [], childNodes: ['O_004'] },
        { currNode: 'P_006', parentNodes: [], childNodes: ['O_006'] },
      ],
    },
    svgResourceConnectionList: [
      {
        targetIdList: ['WW_001', 'WW_002', 'WW_003', 'WW_004', 'WW_005', 'WW_006', 'WW_007'],
        resourceIdList: ['waterWay'],
      },
      {
        targetIdList: [
          'WW_008',
          'WW_009',
          'WW_010',
          'WW_011',
          'WW_012',
          'WW_013',
          'WW_014',
          'WW_015',
          'WW_016',
          'WW_017',
          'WW_018',
          'WW_019',
        ],
        resourceIdList: ['peWaterWay'],
      },
      {
        targetIdList: ['WW_020', 'WW_021', 'WW_035'],
        resourceIdList: ['waterWay_B'],
      },
      {
        targetIdList: ['P_004', 'P_013'],
        resourceIdList: ['underPump'],
      },
      { targetIdList: ['P_001'], resourceIdList: ['overPump'] },
      {
        targetIdList: ['GV_105', 'GV_106'],
        resourceIdList: ['gateValve'],
      },
      {
        targetIdList: ['WD_002', 'WD_004', 'WD_005', 'WD_006', 'WD_007', 'WD_008'],
        resourceIdList: ['waterDoor'],
      },
      {
        targetIdList: ['O_002', 'O_004', 'O_012'],
        resourceIdList: ['outlet'],
      },
      {
        targetIdList: ['S_002'],
        resourceIdList: ['salinity'],
      },
      {
        targetIdList: ['MRT_001'],
        resourceIdList: ['moduleRearTemperature'],
      },
      {
        targetIdList: ['WL_009'],
        resourceIdList: ['waterLevel'],
      },
      { targetIdList: ['BT_001'], resourceIdList: ['brineTemperature'] },
    ],
    hiddenTextSvgModelResourceIdList: ['outlet', 'waterWay'],
  },
  controlInfo: {
    flowCmdList: [
      {
        srcPlaceId: 'RV_1',
        destList: [
          {
            destPlaceId: 'NEB_1',
            trueNodeList: ['P_001'],
            falseNodeList: ['WD_001', 'WD_002', 'WD_003'],
          },
        ],
      },
      {
        srcPlaceId: 'RV_2',
        destList: [{ destPlaceId: 'RV_1', trueNodeList: ['P_002'], falseNodeList: [] }],
      },
      {
        srcPlaceId: 'NEB_1',
        destList: [
          {
            destPlaceId: 'NEB_2',
            trueNodeList: ['WD_002', 'WD_003'],
            falseNodeList: ['WD_001', 'WD_004', 'WD_005', 'WD_006'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['WD_001'], falseNodeList: ['WD_002', 'WD_003'] },
        ],
      },
      {
        srcPlaceId: 'NEB_2',
        destList: [
          { destPlaceId: 'BW_1', trueNodeList: ['WD_005'], falseNodeList: ['WD_004', 'WD_006'] },
          { destPlaceId: 'BW_2', trueNodeList: ['WD_006'], falseNodeList: ['WD_004', 'WD_005'] },
          { destPlaceId: 'SEA', trueNodeList: ['WD_004'], falseNodeList: ['WD_005', 'WD_006'] },
        ],
      },
      {
        srcPlaceId: 'SEB_1',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: ['GV_101', 'GV_105'],
            falseNodeList: ['GV_106', 'GV_104'],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: ['GV_102', 'GV_104', 'GV_105'],
            falseNodeList: ['GV_106', 'GV_101', 'GV_103'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['GV_106'], falseNodeList: ['GV_105'] },
        ],
      },
      {
        srcPlaceId: 'SEB_2',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: ['GV_101', 'GV_107'],
            falseNodeList: ['GV_108', 'GV_104'],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: ['GV_102', 'GV_104', 'GV_107'],
            falseNodeList: ['GV_108', 'GV_101', 'GV_103'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['GV_108'], falseNodeList: ['GV_107'] },
        ],
      },
      {
        srcPlaceId: 'SEB_3',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: ['GV_101', 'GV_109'],
            falseNodeList: ['GV_110', 'GV_104'],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: ['GV_102', 'GV_104', 'GV_109'],
            falseNodeList: ['GV_110', 'GV_101', 'GV_103'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['GV_110'], falseNodeList: ['GV_109'] },
        ],
      },
      {
        srcPlaceId: 'SEB_4',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: ['GV_101', 'GV_111'],
            falseNodeList: ['GV_112', 'GV_104'],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: ['GV_102', 'GV_104', 'GV_111'],
            falseNodeList: ['GV_112', 'GV_101', 'GV_103'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['GV_112'], falseNodeList: ['GV_111'] },
        ],
      },
      {
        srcPlaceId: 'SEB_5',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: ['GV_101', 'GV_113'],
            falseNodeList: ['GV_114', 'GV_104'],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: ['GV_102', 'GV_104', 'GV_113'],
            falseNodeList: ['GV_114', 'GV_101', 'GV_103'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['GV_114'], falseNodeList: ['GV_113'] },
        ],
      },
      {
        srcPlaceId: 'SEB_6',
        destList: [
          {
            destPlaceId: 'BW_3',
            trueNodeList: ['GV_102', 'GV_115'],
            falseNodeList: ['GV_116', 'GV_104', 'GV_103'],
          },
          {
            destPlaceId: 'BW_4',
            trueNodeList: ['GV_103', 'GV_115'],
            falseNodeList: ['GV_116', 'GV_104', 'GV_102'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['GV_116'], falseNodeList: ['GV_115'] },
        ],
      },
      {
        srcPlaceId: 'SEB_7',
        destList: [
          {
            destPlaceId: 'BW_3',
            trueNodeList: ['GV_102', 'GV_117'],
            falseNodeList: ['GV_118', 'GV_104', 'GV_103'],
          },
          {
            destPlaceId: 'BW_4',
            trueNodeList: ['GV_103', 'GV_117'],
            falseNodeList: ['GV_118', 'GV_104', 'GV_102'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['GV_118'], falseNodeList: ['GV_117'] },
        ],
      },
      {
        srcPlaceId: 'SEB_8',
        destList: [
          {
            destPlaceId: 'BW_3',
            trueNodeList: ['GV_102', 'GV_119'],
            falseNodeList: ['GV_120', 'GV_104', 'GV_103'],
          },
          {
            destPlaceId: 'BW_4',
            trueNodeList: ['GV_103', 'GV_119'],
            falseNodeList: ['GV_120', 'GV_104', 'GV_102'],
          },
          { destPlaceId: 'SEA', trueNodeList: ['GV_120'], falseNodeList: ['GV_119'] },
        ],
      },
      {
        srcPlaceId: 'NCB',
        destList: [
          { destPlaceId: 'BW_5', trueNodeList: ['WD_007'], falseNodeList: ['WD_008'] },
          { destPlaceId: 'SEA', trueNodeList: ['WD_008'], falseNodeList: ['WD_007'] },
        ],
      },
      {
        srcPlaceId: 'BW_1',
        destList: [
          {
            destPlaceId: 'NEB_2',
            trueNodeList: ['P_003'],
            falseNodeList: ['WD_004', 'WD_005', 'WD_006'],
          },
        ],
      },
      {
        srcPlaceId: 'BW_2',
        destList: [
          { destPlaceId: 'SEB_1', trueNodeList: ['P_004'], falseNodeList: ['GV_105', 'GV_106'] },
          { destPlaceId: 'SEB_2', trueNodeList: ['P_005'], falseNodeList: ['GV_107', 'GV_108'] },
          { destPlaceId: 'SEB_3', trueNodeList: ['P_006'], falseNodeList: ['GV_109', 'GV_110'] },
          { destPlaceId: 'SEB_4', trueNodeList: ['P_007'], falseNodeList: ['GV_111', 'GV_112'] },
          { destPlaceId: 'SEB_5', trueNodeList: ['P_008'], falseNodeList: ['GV_113', 'GV_114'] },
          {
            destPlaceId: 'SEB_ONE',
            destPlaceName: '수중 태양광 증발지 그룹 1',
            trueNodeList: ['P_004', 'P_005', 'P_006', 'P_007', 'P_008'],
            falseNodeList: [
              'GV_105',
              'GV_106',
              'GV_107',
              'GV_108',
              'GV_109',
              'GV_110',
              'GV_111',
              'GV_112',
              'GV_113',
              'GV_114',
            ],
          },
        ],
      },
      {
        srcPlaceId: 'BW_3',
        destList: [
          { destPlaceId: 'SEB_6', trueNodeList: ['P_009'], falseNodeList: ['GV_115', 'GV_116'] },
          { destPlaceId: 'SEB_7', trueNodeList: ['P_010'], falseNodeList: ['GV_117', 'GV_118'] },
          { destPlaceId: 'SEB_8', trueNodeList: ['P_011'], falseNodeList: ['GV_119', 'GV_120'] },
          {
            destPlaceId: 'SEB_TWO',
            destPlaceName: '수중 태양광 증발지 그룹 2',
            trueNodeList: ['P_009', 'P_010', 'P_011'],
            falseNodeList: ['GV_115', 'GV_116', 'GV_117', 'GV_118', 'GV_119', 'GV_120'],
          },
        ],
      },
      {
        srcPlaceId: 'BW_4',
        destList: [{ destPlaceId: 'BW_5', trueNodeList: ['P_012'], falseNodeList: [] }],
      },
      {
        srcPlaceId: 'BW_5',
        destList: [
          { destPlaceId: 'NCB', trueNodeList: ['P_013'], falseNodeList: ['WD_007', 'WD_008'] },
        ],
      },
      {
        srcPlaceId: 'SEB_ONE',
        srcPlaceName: '수중 태양광 증발지 그룹 1',
        destList: [
          {
            destPlaceId: 'BW_2',
            trueNodeList: ['GV_101', 'GV_105', 'GV_107', 'GV_109', 'GV_111', 'GV_113'],
            falseNodeList: ['GV_104', 'GV_106', 'GV_108', 'GV_110', 'GV_112', 'GV_114'],
          },
          {
            destPlaceId: 'BW_3',
            trueNodeList: ['GV_102', 'GV_104', 'GV_105', 'GV_107', 'GV_109', 'GV_111', 'GV_113'],
            falseNodeList: ['GV_101', 'GV_103', 'GV_106', 'GV_108', 'GV_110', 'GV_112', 'GV_114'],
          },
          {
            destPlaceId: 'SEA',
            trueNodeList: ['GV_106', 'GV_108', 'GV_110', 'GV_112', 'GV_114'],
            falseNodeList: ['GV_105', 'GV_107', 'GV_109', 'GV_111', 'GV_113'],
          },
        ],
      },
      {
        srcPlaceId: 'SEB_TWO',
        srcPlaceName: '수중 태양광 증발지 그룹 2',
        destList: [
          {
            destPlaceId: 'BW_3',
            trueNodeList: ['GV_102', 'GV_115', 'GV_117', 'GV_119'],
            falseNodeList: ['GV_103', 'GV_104', 'GV_116', 'GV_118', 'GV_120'],
          },
          {
            destPlaceId: 'BW_4',
            trueNodeList: ['GV_103', 'GV_115', 'GV_117', 'GV_119'],
            falseNodeList: ['GV_102', 'GV_104', 'GV_116', 'GV_118', 'GV_120'],
          },
          {
            destPlaceId: 'SEA',
            trueNodeList: ['GV_116', 'GV_118', 'GV_120'],
            falseNodeList: ['GV_115', 'GV_117', 'GV_119'],
          },
        ],
      },
    ],
    setCmdList: [
      {
        cmdId: 'closeAllDevice',
        cmdName: '모든 장치 닫기',
        trueNodeList: [],
        falseNodeList: [
          'GV_101',
          'GV_102',
          'GV_103',
          'GV_104',
          'GV_105',
          'GV_106',
          'GV_107',
          'GV_108',
          'GV_109',
          'GV_110',
          'GV_111',
          'GV_112',
          'GV_113',
          'GV_114',
          'GV_115',
          'GV_116',
          'GV_117',
          'GV_118',
          'GV_119',
          'GV_120',
          'WD_001',
          'WD_002',
          'WD_003',
          'WD_004',
          'WD_005',
          'WD_006',
          'WD_007',
          'WD_008',
          'P_001',
          'P_002',
          'P_003',
          'P_004',
          'P_005',
          'P_006',
          'P_007',
          'P_008',
          'P_009',
          'P_010',
          'P_011',
          'P_012',
          'P_013',
        ],
      },
      {
        cmdId: 'rainMode',
        cmdName: '우천 모드',
        trueNodeList: [
          'GV_106',
          'GV_108',
          'GV_110',
          'GV_112',
          'GV_114',
          'GV_116',
          'GV_118',
          'GV_120',
          'WD_001',
          'WD_004',
          'WD_008',
        ],
        falseNodeList: [
          'GV_101',
          'GV_102',
          'GV_103',
          'GV_104',
          'GV_105',
          'GV_107',
          'GV_109',
          'GV_111',
          'GV_113',
          'GV_115',
          'GV_117',
          'GV_119',
          'WD_002',
          'WD_003',
          'WD_005',
          'WD_006',
          'WD_007',
          'P_001',
          'P_002',
          'P_003',
          'P_004',
          'P_005',
          'P_006',
          'P_007',
          'P_008',
          'P_009',
          'P_010',
          'P_011',
          'P_012',
          'P_013',
        ],
      },
    ],
    scenarioCmdList: [
      {
        cmdId: 'rainMode',
        cmdName: '우천 대피',
        scenarioList: [
          { wrapCmdFormat: 'SET', wrapCmdType: 'CONTROL', setCmdId: 'closeAllDevice' },
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: {
                  goalDataList: [{ nodeId: '', goalValue: 1, goalRange: 'LOWER' }],
                },
                flowSrcPlaceId: 'NCB',
                flowDestPlaceId: 'BW_5',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                flowSrcPlaceId: 'NCB',
                flowDestPlaceId: 'SEA',
              },
            ],

            {
              wrapCmdFormat: 'FLOW',
              wrapCmdType: 'CONTROL',
              wrapCmdGoalInfo: {
                goalDataList: [
                  { nodeId: 'WL_014', goalValue: 2, goalRange: 'LOWER' },
                  { nodeId: 'WL_015', goalValue: 2, goalRange: 'LOWER' },
                  { nodeId: 'WL_016', goalValue: 2, goalRange: 'LOWER' },
                ],
              },
              flowSrcPlaceId: 'SEB_TWO',
              flowDestPlaceId: 'BW_3',
            },
            {
              wrapCmdFormat: 'FLOW',
              wrapCmdType: 'CONTROL',
              flowSrcPlaceId: 'SEB_TWO',
              flowDestPlaceId: 'SEA',
            },
          ],
          [
            {
              wrapCmdFormat: 'FLOW',
              wrapCmdType: 'CONTROL',
              wrapCmdGoalInfo: {
                goalDataList: [
                  { nodeId: 'WL_009', goalValue: 2, goalRange: 'LOWER' },
                  { nodeId: 'WL_010', goalValue: 2, goalRange: 'LOWER' },
                  { nodeId: 'WL_011', goalValue: 2, goalRange: 'LOWER' },
                  { nodeId: 'WL_012', goalValue: 2, goalRange: 'LOWER' },
                  { nodeId: 'WL_013', goalValue: 2, goalRange: 'LOWER' },
                ],
              },
              flowSrcPlaceId: 'SEB_ONE',
              flowDestPlaceId: 'BW_2',
            },
            {
              wrapCmdFormat: 'FLOW',
              wrapCmdType: 'CONTROL',
              flowSrcPlaceId: 'SEB_ONE',
              flowDestPlaceId: 'SEA',
            },
          ],
          [
            {
              wrapCmdFormat: 'FLOW',
              wrapCmdType: 'CONTROL',
              wrapCmdGoalInfo: {
                goalDataList: [{ nodeId: 'WL_004', goalValue: 2, goalRange: 'LOWER' }],
              },
              flowSrcPlaceId: 'NEB_2',
              flowDestPlaceId: 'BW_1',
            },
            {
              wrapCmdFormat: 'FLOW',
              wrapCmdType: 'CONTROL',
              flowSrcPlaceId: 'NEB_2',
              flowDestPlaceId: 'SEA',
            },
          ],
          [
            {
              wrapCmdFormat: 'FLOW',
              wrapCmdType: 'CONTROL',
              flowSrcPlaceId: 'NEB_1',
              flowDestPlaceId: 'SEA',
            },
          ],
          {
            wrapCmdFormat: 'SET',
            wrapCmdType: 'CONTROL',
            setCmdId: 'rainMode',
          },
        ],
      },
      {
        cmdId: 'normalFlowScenario',
        cmdName: '소금 생산 시나리오',
        scenarioList: [
          { wrapCmdFormat: 'SET', wrapCmdType: 'CONTROL', setCmdId: 'closeAllDevice' },
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'RV_2',
                flowDestPlaceId: 'RV_1',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                flowSrcPlaceId: 'RV_2',
                flowDestPlaceId: 'RV_1',
              },
            ],
          ],
          [
            [
              {
                wrapCmdFormat: 'SINGLE',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                singleNodeId: ['P_001', 'WD_002', 'WD_003'],
                singleControlType: 1,
              },
              {
                wrapCmdFormat: 'SINGLE',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                singleNodeId: ['P_001', 'WD_002', 'WD_003'],
                singleControlType: 0,
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'NEB_2',
                flowDestPlaceId: 'BW_2',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'NEB_2',
                flowDestPlaceId: 'BW_2',
              },
            ],
          ],
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_2',
                flowDestPlaceId: 'SEB_ONE',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_2',
                flowDestPlaceId: 'SEB_ONE',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'SEB_ONE',
                flowDestPlaceId: 'BW_3',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                flowSrcPlaceId: 'SEB_ONE',
                flowDestPlaceId: 'BW_3',
              },
            ],
          ],
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_3',
                flowDestPlaceId: 'SEB_TWO',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_3',
                flowDestPlaceId: 'SEB_TWO',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'SEB_TWO',
                flowDestPlaceId: 'BW_4',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                flowSrcPlaceId: 'SEB_TWO',
                flowDestPlaceId: 'BW_4',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_4',
                flowDestPlaceId: 'BW_5',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                flowSrcPlaceId: 'BW_4',
                flowDestPlaceId: 'BW_5',
              },
            ],
          ],
          [
            [
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CONTROL',
                wrapCmdGoalInfo: { limitTimeSec: 9 },
                flowSrcPlaceId: 'BW_5',
                flowDestPlaceId: 'NCB',
              },
              {
                wrapCmdFormat: 'FLOW',
                wrapCmdType: 'CANCEL',
                flowSrcPlaceId: 'BW_5',
                flowDestPlaceId: 'NCB',
              },
            ],
          ],
        ],
      },
    ],
    tempControlList: [{ cmdName: '', trueList: [], falseList: [] }],
  },
};

module.exports = map;
